### PR TITLE
Add multi-tab support

### LINKED ISSUE #93: Add full multi-tab support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

As the title.
part of the 0.9.x shipment.
This is what I consider the most important feature of this application. So I will upgrade to v1.0.0 once this change is stable.
And GitHub data changes called "mutations" (file uploads, user following, etc.) will be complete by v2.0.0

### Alternative solutions

*none*

### Relevant Assets

*none*

### PR DESCRIPTION
**Pull request by luandersonn**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes 
#93 
### Details of Changes

- [x] Open tabs
- [x] Close tab
- [x] Go back/forward (navigation history)
- [x] Set tab header
- [x] Set tab icon
- [x] Set window title

### Validation

- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### Relevant Assets

Set Header, description, and Icon
image

Set window title
image

### CODE REVIEW

**Comment by onein528** [comment]
woooow, that's incredible! I was working on this feature in GU4, but will revert them. this is far better than mine.

**Review by trustedmember — APPROVED** [review]

**Review by onein528 — APPROVED** [review]
Absolutely, LGTM.

**Comment by luandersonn** [comment]
@onein528 Merge available

**Review by onein528 — APPROVED** [review]
Nice!

**Pull request merged**
