### PR TITLE
Update English: Grammar, Punctuation & Spelling

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
## Description

As the title

## Motivation and Context

As the title

## Relevant assets (if appropriate):

_None_

### CODE REVIEW

**Comment by onein528** [comment]
GREATE JOB!!!!

**Review by onein528 — APPROVED** [review]
LGTM.

**Comment by DeveloperWOW64** [comment]
> LGTM.

Hmm.. The azure pipelines build failed though.

**Comment by onein528** [comment]
No no dont worry.

When you create a PR from a fork repository, that cannot access the secure files and Pipelines fails. This is not a code change and can be merged immediately with administrator privileges.

**Comment by onein528** [comment]
> > LGTM.
> 
> Hmm.. The azure pipelines build failed though. Edit: Oh wait it's because of AppCredentials.config

Yes. that's one of the secure files.

**Comment by onein528** [comment]
Do you have more updates?

**Comment by DeveloperWOW64** [comment]
> Do you have more updates?

No, none right now

**Comment by onein528** [comment]
Can I merge?

**Comment by DeveloperWOW64** [comment]
> Can I merge?

Yep

**Comment by onein528** [comment]
Thank you!

**Pull request merged**
