### PR TITLE
Multiaccount support

### LINKED ISSUE #8: Add multi-account support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

_No response_

### Expected behavior

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by BobbyESP**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues
- Closes #8 (Wow, the 8th issue haha)

### Details of Changes

- Added the ability to switch between different GitHub accounts without singing out.

### Validation
In the appbar click on the 3 dots icon and in that flyout click on "Switch Account"

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### Relevant Assets
image

### CODE REVIEW

**Comment by onein528** [comment]
why this PR have other PR's diff?

**Comment by BobbyESP** [comment]
Because i've made the branch based on yours but it's weired...

**Comment by onein528** [comment]
high possibility to occur conflict.. sorry but can you change "merge to"? maybe you cannot update tis branch so you need to merge to issuepr-event branch and I will rename title to General Updates 7.

**Comment by BobbyESP** [comment]
> high possibility to occur conflict.. sorry but can you change "merge to"? maybe you cannot update tis branch so you need to merge to issuepr-event branch and I will rename title to General Updates 7.

Ok! Letme try one thing by the way

**Pull request closed without merging**
