### PR TITLE
Add JumpList support

### LINKED ISSUE #96: Add JumpList support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

Create a JumpList of common pages and actions
Capability | Priority
:-- | :--:
Navigate to user pages (Profile, Notifications, Activities, etc.) | Must
Allow the user to pin any repository | Could
Allow account switching | Could

### Alternative solutions

_No response_

#### Preview
image

### PR DESCRIPTION
**Pull request by luandersonn**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #96 

### Details of Changes
Add JumpList to some pages [not working yet]

#### Milestones
- [x] Add icons supporting multiple sizes
- [x] Localization
- [x] Navigate to user pages (Profile, Notifications, Activities, etc.)
 - [ ] ~~Allow the user to pin any repository~~
- [ ] ~~Allow account switching~~

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

#### Preview 1
Screenshot-1

#### Update tab icons
image

### CODE REVIEW

**Comment by onein528** [comment]
wow.. definitely incredible! i'm gonna add i18n resources!

**Comment by onein528** [comment]
well, i am not familiar with jump list items. so i dont know what happened

image

**Comment by onein528** [comment]
```cs
var prefix = "ms-appx:///Assets/JumpListIcons";
var item = CreateJumpListItem("Profile", "Profile".GetLocalized(), $"{prefix}/Profile.png", "", "Profile");
jumpList.Items.Add(item);
item = CreateJumpListItem("Notifications", "Notifications".GetLocalized(), $"{prefix}/Notifications.png", "", "Profile");
jumpList.Items.Add(item);
item = CreateJumpListItem("Activities", "Activities".GetLocalized(), $"{prefix}/Activities.png", "", "Profile");
jumpList.Items.Add(item);
item = CreateJumpListItem("Issues", "Issues".GetLocalized(), $"{prefix}/Issues.png", "", "My Work");
jumpList.Items.Add(item);
item = CreateJumpListItem("Pull Requests", "PullRequests".GetLocalized(), $"{prefix}/PullRequests.png", "", "My Work");
jumpList.Items.Add(item);
item = CreateJumpListItem("Discussions", "Discussions".GetLocalized(), $"{prefix}/Discussions.png", "", "My Work");
jumpList.Items.Add(item);
item = CreateJumpListItem("Repositories", "Repositories".GetLocalized(), $"{prefix}/Repositories.png", "", "My Work");
jumpList.Items.Add(item);
item = CreateJumpListItem("Organizations", "Organizations".GetLocalized(), $"{prefix}/Organizations.png", "", "My Work");
jumpList.Items.Add(item);
item = CreateJumpListItem("Starred", "Starred".GetLocalized(), $"{prefix}/Starred.png", "", "My Work");
jumpList.Items.Add(item);
await jumpList.SaveAsync();
```

it's good?

**Comment by onein528** [comment]
you can localize like `"PullRequests".GetLocalized();` adding `using Microsoft.Toolkit.Uwp;`

**Comment by luandersonn** [comment]
Yeah, updated

Luandersonn Airton
________________________________
De: NullPointerException ***@***.***>
Enviado: quinta-feira, 17 de março de 2022 20:01
Para: fluenthub-community/FluentHub ***@***.***>
Cc: Luandersonn Airton ***@***.***>; Author ***@***.***>
Assunto: Re: [fluenthub-community/FluentHub] Add JumpList support (PR #97)


well, i am not familiar with jump list items. so i dont know what happened

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F62196528%2F158907865-4efedcc6-dc81-4528-98ab-8d82a4dcbd0e.png&data=04%7C01%7C%7C7f2afe34036d4a3cfa3108da086a0d38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831548844830842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g9j4euG0vAFt2uUwMN1MLJszW2b3Wi42TO9LrBhKCj0%3D&reserved=0>

**Comment by luandersonn** [comment]
@onein528 When a JumpListItem is invoked, how do you think the app should proceed?
[ ] Open the page in current tab
[ ] Open the page in new tab

**Comment by onein528** [comment]
I think continueing with new tab is good.

**Review by onein528 — DISMISSED** [review]

**Review by onein528 — APPROVED** [review]

**Comment by luandersonn** [comment]
The app now handle activation like` fluenthub://issues`,` fluenthub://settings` and `fluenthub://settings?page=about`, but only if the app is already running

**Comment by onein528** [comment]
ok.

**Pull request merged**
