### PR TITLE
General Updates 4

### LINKED ISSUE #93: Add full multi-tab support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

As the title.
part of the 0.9.x shipment.
This is what I consider the most important feature of this application. So I will upgrade to v1.0.0 once this change is stable.
And GitHub data changes called "mutations" (file uploads, user following, etc.) will be complete by v2.0.0

### Alternative solutions

*none*

### Relevant Assets

*none*

### PR DESCRIPTION
**Pull request by onein528**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #93 

### Details of Changes

`Major version will be updated(v0.9.x)`

Description|Priority|Status
---|---|---
Add full multi-tab support <co-authored by @luandersonn>|Must|Done
Update issue b/b state glyph coloring|Must|Done
Update PR b/b state glyph coloring|Must|Done
Update notification b/b state glyph coloring|Must|Done
Rename OctikitEx with Octokit||Done
Delete unused source files||Done

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
This PR will be abandon.

**Comment by onein528** [comment]
sorry

**Comment by onein528** [comment]
change log:
```
+ Rename FluentHub.OctokitEx with FluentHub.Octokit
+ Rename confusing class names in FluentHub.Octokit
+ Move Activity data acquisition class to FluentHub.Octokit
+ Simplify class names
+ Add multi-tab support
- Delete unused class files
+ Improve viewer's activities page
+ Add new member's credit
+ Color the status glyph of the issue/PR/notification's button block
```

**Comment by onein528** [comment]
could not reach v0.9.x

**Review by trustedmember — DISMISSED** [review]

**Comment by trustedmember** [comment]
To-Do:

- CodeFactor

**Review by trustedmember — APPROVED** [review]
LGTM shipit v0.8.25

**Pull request merged**
