### PR TITLE
General Updates 7

### LINKED ISSUE #130: App have unhandled exception Cannot convert Null to Int32
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Beta

### What FluentHub version/architecture are you seeing the problem on?

0.7.13.0 | X64 | DEBUG

### Description

Just fetched and it fixed #123 but it created another issue that I can't go to another person's GitHub or to the home via URL. Basically, you can't change the URL to another person's GitHub or to the home.

### Steps To Reproduce

1. Type something on the URL and hit enter

### Expected behavior

What I expected to happen was that it changes to the URL you gave.

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by onein528**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #130 

### Details of Changes

- Fixed an issue where does not display labels of issue/PR button properly.
- Fixed viewer notification page.

### Validation

- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
## What's new

2a069f8 Updated header of issue/PR page

image

**Comment by onein528** [comment]
## What's new

Added archive message on the top of repository view

image

Added discussions page(project discussion is unavailable) (need to create the table of all discussion emoji)

image

Added projects page(project page is unavailable)

image

**Comment by onein528** [comment]
## What's new (previous change)

Added settings page's mock-up controls

image

image

**Review by FluentHub-Observer — COMMENTED** [review]
LGTM

**Pull request merged**
