### PR TITLE
General Updates 5

### LINKED ISSUE #100: Add keyboard shortcut support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

Adding support for keyboard and mouse shortcuts would increase productivity with FluentHub.

Common shortcuts:

Shortcut | Description
:-|:-
`Ctrl` + `T` | Opens a new tab
`Ctrl` + `W` | Closes the current tab
`Ctrl` + `Tab` | Go to the next tab
`Ctrl` + `Shift` + `Tab` | Go to the previous tab
`Alt` + `Left`, `Back` (mouse) | Navigate back
`Alt` + `Right`, `Forward` (mouse) | Navigate forward
`F5` | Refresh the page

And more

### Alternative solutions

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by onein528**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #100 (maybe)

### Details of Changes

_None yet_

### Validation

- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Review by luandersonn — COMMENTED** [review]
I just added the suffix "Async" to the name of the async method

**Review by luandersonn — APPROVED** [review]

**Comment by onein528** [comment]
updated tab:

image

**Comment by onein528** [comment]
to do:

- update code base of the readme content block to view model base.
- update an issue/PR page(issue/PR's event getter will be on FluentHub.Octokit)
- update repo's code page(details view)

**Comment by luandersonn** [comment]
Love it

**Comment by luandersonn** [comment]
Sorry

**Comment by onein528** [comment]
ok, will marge, other goals will be update on next PRs.

**Comment by onein528** [comment]
and can you see discord? i have been asked a question.

**Review by trustedmember — APPROVED** [review]

**Pull request merged**
