### PR TITLE
Update implementation of navigation between tabs

### LINKED ISSUE #110: Navigate incorrect frame
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

v0.7.13 (deving)

### Description

When returning to the previous frame, it does not go to the previous sub-frame page.

### Steps To Reproduce

1. click an issue/pr button
or
1. go to code view

### Expected behavior

navigate correct sub frame

### Relevant Assets

image

image

### PR DESCRIPTION
**Pull request by luandersonn**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes  #110 

### Details of Changes

In early versions, navigation of the entire application was performed using only one frame for all tabs. This led to some problems:
- The browsing history needed to be removed and added to `Frame`'s browsing stack every time there is a tab change.
- The page does not save any data, for example the position of the `ScrollViewer` or the page loaded in any nested `Frame`. Web requests needed to be repeated.

In this update, the following changes have been made:
- Each `ITabViewItem` has its own frame and is responsible for its navigation.
- The app should remove and add the `ITabViewItem`'s Frame from the UI when the tab selection changes.

Other changes:
- Tab reorder support

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
very nice! and i can move from onloaded to viewmodel

**Comment by luandersonn** [comment]
> very nice! and i can move from onloaded to viewmodel

Yes, using the Command pattern and triggering on `OnNavigated` event.

**Comment by onein528** [comment]
i will fix code content loading on this branch.

**Comment by onein528** [comment]
image

i fixed navigation but does not recored navigation history(new issue?).

**Comment by onein528** [comment]
### New

Fixed primary language and license querying and updated star button

image

**Comment by onein528** [comment]
## New changes

7e1b968 New look of repo overview on top

- Public/Private label
- branch/tag count
- star/unstar button

image

**Review by onein528 — DISMISSED** [review]
So far, Tab frames does work property!

**Comment by onein528** [comment]
@luandersonn Are you ready to merge?

**Comment by luandersonn** [comment]
No

**Comment by onein528** [comment]
@Luandersonn should update usercontrol vm to DI? but i don't know how to do. can you give me example(pls update FileNavigationBlockViewModel uc vm)?

**Comment by luandersonn** [comment]
> @luandersonn should update usercontrol vm to DI? but i don't know how to do. can you give me example(pls update FileNavigationBlockViewModel uc vm)?

Only if the VM uses services (like `ILogger`, `IMessenger`...)

**Comment by onein528** [comment]
maybe use those.

**Comment by luandersonn** [comment]
I need more context

**Comment by onein528** [comment]
ahh, yes. I can update uc vm to DI. but I dont know where should I run command like IssueCommentBlockCommand. there is no OnNavigatedTo. so...

**Review by onein528 — APPROVED** [review]
LGTM. Thank you!

**Comment by luandersonn** [comment]
> ahh, yes. I can update uc vm to DI. but I dont know where I should run command like IssueCommentBlockCommand. there is no OnNavigatedTo. so...
> 
> ```cs
> var command = ViewModel.RefreshDiscussionsCommand;
> if (command.CanExecute(DataContext))
>     command.Execute(DataContext);
> ```

OnLoaded

**Pull request merged**
