### PR TITLE
General Updates

### PR DESCRIPTION
**Pull request by onein528**
`Attention: This contains breaking changes. maybe there are many bugs in this changes.`

**Resolved / Related Issues**

_None_

**Details of Changes**

```
+ [infra] move project files to src/**
+ [infra] move docs to docs/** folder
+ [infra] move logo location from AppTiles/** to AppTilesDev/**
+ Update issue/PR templates
+ Add GitHub Actions(disabled)
+ Reduce slowdown in loading repo content
+ Update and rename Privacy Policy.md to Privacy.md
+ Update README.md
+ Add file navigation on top of repository code contents view
+ Update azure pipelines yaml files
+ Add org flyout card mock-up control
+ Add followers/following pages and extensions
+ Add FluentHub.OctokitEx class library
+ Update UI generally
```

The bugs are needed to fix:

- repo view deadlock
- issue/PR pages runtime error

**Validation**

- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Review by BobbyESP — APPROVED** [review]
Lgtm

**Comment by BobbyESP** [comment]
I think so, i'll try to fix it.

**Comment by onein528** [comment]
oppps. i renamed this org name. then, azure pipeplines does not work property.
I will re-create in another PR.

**Review by BobbyESP — DISMISSED** [review]
All seems good! And for what i see, you fixed the stars/PRs/repos bug. I've also made that fix but i forgot to commit it kek, no problem. Nice!

**Comment by onein528** [comment]
NoNo, I have only reduced the problem of slow loading of the repository content ListView.

So far, I cannot find solution to that problem yet.

**Comment by BobbyESP** [comment]
Ahh ok. I dont really know what happens. I dont think it's our problem, but we might try to find a temporal fix. The request is weired....

**Comment by onein528** [comment]
ok. i am under arrent by exams :(( and I will resume on 3/10 fully. then I will find solution.

**Comment by BobbyESP** [comment]
Yeahh, no problem! Good luck with them, i hope the best for you!

**Comment by onein528** [comment]
Thank you!! I do my best!!

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
Organization flyout

image

**Comment by BobbyESP** [comment]
Really nice all that changes!

**Review by BobbyESP — APPROVED** [review]
Looks good to me.

**Comment by onein528** [comment]
currently. repository issue/PR page is buggy and cases RT error. sorry I'll fix later but not now.

**Comment by BobbyESP** [comment]
Yeah men, no problem!  Sorry for not being active at these days :( I'm very busy as you :(

**Review by BobbyESP — DISMISSED** [review]
All seems good to me! And nice change that about the GraphQL requests

**Comment by BobbyESP** [comment]
I dont know how hard the school is in there, but here... Omg, i cant do anything away from the school lol, i have no time

**Comment by onein528** [comment]
that's no problem! good luck in your school!

**Comment by BobbyESP** [comment]
Ohh thanks men! And keep it going! It will be a great app and i'll be coding when i'm ableª

**Comment by onein528** [comment]
yess! thank you.
Up until now and from now on I want to maintain this project!

**Comment by onein528** [comment]
:shipit: v0.8.3

**Comment by onein528** [comment]
now :)

```diff

+3,783
-4,510

```

**Review by trustedmember — APPROVED** [review]

**Comment by trustedmember** [comment]
Needed to improve:

- Repo view deadrock

**Review by trustedmember — APPROVED** [review]

**Comment by trustedmember** [comment]
final needed to fix issues:

- issue/PR views exception

**Review by trustedmember — APPROVED** [review]

**Comment by onein528** [comment]
image

image

image

**Comment by onein528** [comment]
ALL DONE! THIS IS ALREADY FOR YOUR REVIEW!!!

**Review by trustedmember — APPROVED** [review]

**Comment by onein528** [comment]
change log:

```
+ [infra] move project files to src/**
+ [infra] move docs to docs/** folder
+ [infra] move logo location from AppTiles/** to AppTilesDev/**
+ [infra] change `*ListPath` to `*esPage`
+ Update issue/PR templates
+ Add GitHub Actions(disabled)
+ Reduce slowdown in loading repo content
+ Update and rename Privacy Policy.md to Privacy.md
+ Update README.md
+ Add file navigation on top of repository code contents view
+ Update azure pipelines yaml files
+ Add org flyout card mock-up control
+ Add followers/following pages and extensions
+ Add FluentHub.OctokitEx class library
+ Fix some issue/PR page issues
+ Update UI generally
```

**Comment by onein528** [comment]
very exciting to release this updates!

image

**Comment by onein528** [comment]
sorry some critical errors were fixed. no more commits. I'll sleep:) (now 4:01 AM)

**Comment by onein528** [comment]
I need your review @BobbyESP

**Comment by onein528** [comment]
But it seems that we need to merge as soon as possible so I will merge.

**Review by trustedmember — APPROVED** [review]

**Pull request merged**
