### PR TITLE
Add keyboard shortcuts

### LINKED ISSUE #100: Add keyboard shortcut support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

Adding support for keyboard and mouse shortcuts would increase productivity with FluentHub.

Common shortcuts:

Shortcut | Description
:-|:-
`Ctrl` + `T` | Opens a new tab
`Ctrl` + `W` | Closes the current tab
`Ctrl` + `Tab` | Go to the next tab
`Ctrl` + `Shift` + `Tab` | Go to the previous tab
`Alt` + `Left`, `Back` (mouse) | Navigate back
`Alt` + `Right`, `Forward` (mouse) | Navigate forward
`F5` | Refresh the page

And more

### Alternative solutions

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by luandersonn**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes #100

### Details of Changes

Shortcut | Description | Status
:-|:-|:-:
`Ctrl` + `T` | Opens a new tab | ✅
`Ctrl` + `W` | Closes the current tab | ✅
`Ctrl` + `Tab` | Go to the next tab | ✅
`Ctrl` + `Shift` + `Tab` | Go to the previous tab | ✅
`Alt` + `Left` | Navigate back | ✅
`Alt` + `Right` | Navigate forward | ✅
`Back` (mouse) | Navigate back | ✅
`Forward` (mouse) | Navigate forward | ✅
`F5` | Refresh the page | ❌

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
can i merge?

**Review by onein528 — APPROVED** [review]
Greate job!

**Comment by luandersonn** [comment]
You can merge if you have no other shortcuts to add to the list

**Comment by onein528** [comment]
Looks greate, will merge.

**Pull request merged**
