### PR TITLE
Portuguese (Portugal) Translation

### PR DESCRIPTION
**Pull request by esibruti**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Details of Changes

- Added Portuguese (Portugal) translation

### Validation

- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
ohh. i'm sorry, but in next release, delete all localization resources due to breaking changes. take a look add-logs branch(current newest branch)

**Comment by onein528** [comment]
but you dont have to close this.　Will review this again when stable.

**Review by onein528 — APPROVED** [review]
LGTM

**Comment by esibruti** [comment]
I didn't know that was the most current one (add-logs). But this way it's ready for later :)

**Pull request closed without merging**
