### PR TITLE
Update tiny SPaG mistake

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
## Description

As the title

## Motivation and Context

As the title

## Relevant assets (if appropriate):

_None_

### CODE REVIEW

**Review by onein528 — COMMENTED** [review]
Why added to the end of the line?

**Comment by DeveloperWOW64** [comment]
> Why added to the end of the line?

Its just english grammar: dont ask me

**Comment by onein528** [comment]
Please describe more details.

**Comment by onein528** [comment]
> > Why added to the end of the line?
> 
> Its just english grammar: dont ask me

I didnt know about that.

**Comment by DeveloperWOW64** [comment]
> I didnt know about that.

https://www.grammarly.com/blog/semicolon/

**Pull request merged**
