### PR TITLE
General Updates 6

### PR DESCRIPTION
**Pull request by onein528**
**`General Updates round 6 is very very huge breaking changes.`**

### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Details of Changes

- Fixed coloring of user contribution graph
- Added svg image when there's no available item
- Added branch selector
- Added release list page
- Added repository meta sidebar
- Added commit list page
- Added commit page
- Added label group to issue/PR button block
- Improved repository button block contents
- Updated issue/PR event getter and block (is almost of 10k code changes)

### Validation

- [x] Built and ran the app
- [ ] Tested the changes for accessibility

### Relevant Assets

image

### CODE REVIEW

**Comment by onein528** [comment]
## What's changed

Enabled branch selector and it works property

image

**Comment by BobbyESP** [comment]
Wow, can you send a screenshot about that last commit?

**Comment by onein528** [comment]
@BobbyESP This? `Added repository meta sidebar mock-up`

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
## What's new

First look of release list page

image

**Comment by onein528** [comment]
## What's changed

64b8cd2 Added issue label gorup

image

**Comment by onein528** [comment]
## Wchat's changed

Added reviews/checks labels

image

**Comment by onein528** [comment]
New repository sidebar looks

image

New repository releases looks

image

**Comment by onein528** [comment]
New looks of repo button block

image

**Comment by BobbyESP** [comment]
Nice changes!

**Comment by onein528** [comment]
## What's new

c703238 Added commit page user specified

The first look of commit page:
image

**Comment by onein528** [comment]
## What's new

I have very exciting changes! Added addition/deletion coloring

image

image

**Comment by onein528** [comment]
Diff patch blocks does nice work

image

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
### What's changed

Improved issue event block to get more efficient(add other than comments):

image

**Comment by onein528** [comment]
Issue event blocks does work good.

image

**Comment by onein528** [comment]
Label event displaying sample:

image

**Comment by onein528** [comment]
@BobbyESP @luandersonn
Do you have other commits or suggestions? If you two not, I will do final adjustment and then merge this.

**Comment by onein528** [comment]
Since issue/PR event getter got very complex method, CodeFactor failed, but doesn't matter I think.

**Comment by luandersonn** [comment]
> @BobbyESP @luandersonn Do you have other commits or suggestions? If you two not, I will do final adjustment and then merge this.

You can merge.

**Comment by onein528** [comment]
@BobbyESP Do you?

**Comment by BobbyESP** [comment]
> @BobbyESP Do you?

No, continue. I have an idea but it's not done

**Review by FluentHub-Observer — APPROVED** [review]

**Comment by FluentHub-Observer** [comment]
change-log:

```
Added svg image when there's no available item
Added release list page
Added repository meta sidebar
Added commit list page
Added commit page
Added diff content block
Added label group to issue/PR button block
Enabled branch selector
Fixed coloring of user contribution graph
Improved repository button block contents
Updated issue/PR event query and block
```

**Pull request merged**
