### PR TITLE
Added sideload azure pipeline

### PR DESCRIPTION
**Pull request by onein528**

### CODE REVIEW

**Comment by onein528** [comment]
[cannot open CA certificate file](https://dev.azure.com/fluenthub-community/FluentHub/_build/results?buildId=480&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef&l=1293)

@BobbyESP Do you know how to fix?

**Comment by BobbyESP** [comment]
I'm seeing what we can do with that

**Comment by BobbyESP** [comment]
https://user-images.githubusercontent.com/60316747/161385060-985efc0e-e982-4205-9ca6-f0ee462f0e5d.mp4
These fays im not able to work a lot so im refactoring the login page. It has some bugs and it's literally empty, so...

**Comment by onein528** [comment]
this is concept? if you do continue like this intropage, i think it seems to it's little bit bad. And I know you have to study every day, so take it easy men ;) I do definetely absolutely NOT remove definetely absolutely from this community, even if you do nothing at all for days.

**Comment by BobbyESP** [comment]
> this is concept? if you do continue like this intropage, i think it seems to it's little bit bad. And I know you have to study every day, so take it easy men ;) I do definetely absolutely NOT remove definetely absolutely from this community, even if you do nothing at all for days.

Awww men, really thanks!! And ok, no problem about the concept.

**Comment by onein528** [comment]
@BobbyESP Need your review

**Review by BobbyESP — APPROVED** [review]
Seems good!

**Pull request merged**
